title = "ByteNet"
gitRepoUrl = "https://github.com/ffrostflame/bytenet/"

changelog = true

[docusaurus]
projectName = "ByteNet"
tagline = "description"

[footer]
style = "dark"

[home]
enabled = false
includeReadme = false

[[home.features]]
title = "Cuts out Roblox overhead"
description = "You decide what you're sending. Supports uint8, int16, etc."

[[home.features]]
title = "Strictly typed"
description = "Written purely in Luau, for Luau"

[[home.features]]
title = "Simple"
description = "Easy to learn quickly"